### PR TITLE
Update runtime to 23.08, do some housekeeping and add comments for clarity.

### PR DESCRIPTION
**Pull request by ProjectSynchro**
I would have split this into multiple commits, but it was easier to just dump the changes all at once.

When built this works on my system (Fedora Rawhide with AMD Graphics) for hardware acceleration, and there aren't any visible issues with the frontend, nor any missing libraries.

~~I changed up how the flatpak is built, as it's better to not ship ar and it's libraries with the final flatpak just to extract what is essentially a tarball. Additionally I have switched to the upstream icon as this may be changed by parsec and it makes sense to use.~~

The final flatpak only ships the needed libraries and the binary, and saves a tiny bit of time by skipping the build of the unneeded turbojpeg library.

Let me know if you'd like any additional changes, and testers are welcome!

### CODE REVIEW

**Comment by ProjectSynchro** [comment]
bot, build.

**Comment by SISheogorath** [comment]
Well, does parsec publish it's binary under a license that allows redistribution? Otherwise this is not legal. That's exactly why we use extra data so flathub does not redistribute the binary.

**Comment by ProjectSynchro** [comment]
> Well, does parsec publish it's binary under a license that allows redistribution? Otherwise this is not legal. That's exactly why we use extra data so flathub does not redistribute the binary.

That is a good question, I haven't explicitly seen anything in the TOS that mentions redistribution.

I asked ChatGPT about it (granted, it's not a lawyer), and it told me this:

> Yes, repackaging the software, even unaltered, for the purpose of running on another Linux distribution would break these terms. Here's why:

    Non-Transferable License: Both sections 3.2 and 3.3 explicitly state that the license is non-transferable. Repackaging the software and distributing it to others, even unaltered, would constitute transferring the software, which is not permitted.

    Non-Sublicensable: The terms prohibit sublicensing, meaning you cannot grant another person or entity the rights to use the software, which would occur if you redistributed the repackaged software.

    Personal or Internal Business Use: The licenses granted are strictly for personal or internal business purposes. Redistribution, even for a compatible Linux distribution, would be outside the scope of "personal or internal business use."

Therefore, repackaging and distributing the software, even if unaltered, would violate the terms of the agreement.


What may help is asking for written permission to redistribute the binary in an unaltered form (It is untouched from it's binary release)

Otherwise, doing the extraction and install at install time would be the only option.

**Comment by ProjectSynchro** [comment]
@Kodikuu is an employee at Parsec AFAIK, maybe they may be able to give some insights. :smile:

**Comment by ProjectSynchro** [comment]
Looking around on Parsec's Discord for some discourse on the subject brought me to the discussion about nixOS packaging. This is a pretty concrete no (As of 2021): https://discord.com/channels/275729591505780736/275729591505780736/924258856366919681

image


I've adjusted the flatpak manifest to use extra-data, and have at least gotten rid of the requirement to package ar with the final flatpak.

**Comment by Kodikuu** [comment]
I'd meant to do this myself, but work and other things have kept me rather too busy as of late.

I'm no lawyer, but I'm pretty certain that no, this package can't distribute our binaries, and I cannot provide any permission to do so myself. I've deleted the two test builds that do so.

I'll try this test build later in the week under WSL to see if Nvidia will work, and on my AMD Framework for good measure

**Comment by ProjectSynchro** [comment]
> I'd meant to do this myself, but work and other things have kept me rather too busy as of late.
> 

Tis the joy of open source stuff sometimes :smile: 
At the very least applying some of these changes with the current freedesktop runtime would be a good thing compared to how it's packaged ATM, assuming things don't go well.

> I'm no lawyer, but I'm pretty certain that no, this package can't distribute our binaries, and I cannot provide any permission to do so myself. I've deleted the two test builds that do so.

That is what I gathered as well, makes sense and glad it was clarified.

> 
> I'll try this test build later in the week under WSL to see if Nvidia will work, and on my AMD Framework for good measure

Sweet, it does appear that the application does look for `libvdpau_nvidia.so`, so I'm assuming the nvidia extension that is installed for NVIDIA machines should help get that working.

**Comment by Kodikuu** [comment]
While both the original debian package on Ubuntu and this updated flatpak manage to use FFMPEG 6 successfully, the flatpak fails to recognise the "Hardware" and "NVIDIA" decoder options on my WSL2 instance that the normal debian install is able to see within same instance.

The Hardware option fails on the Ubuntu install, because it's actually just Vulkan mis-reporting support to FFMPEG, but NVIDIA works.
The Flatpak is left with only Software support

**Comment by ProjectSynchro** [comment]
Interesting.. the fact that FFMPEG 6 is being used is a good thing. This means it's touching the codecs from the ffmpeg extension, do you know if all of the VAAPI bits are installed on your WSL2 VM? 

I'm not sure how the AMD hardware you have is being abstracted into the VM, but in a standard install of debian for example, you'd need [mesa-va-drivers](https://packages.debian.org/mesa-va-drivers) to provide all of the libraries for applications on the host, I'd be willing to bet something like that is already installed.

What kind of output does running [vainfo](https://packages.debian.org/vainfo) give you in WSL2? Is it possible that there's some kind of missing codec in the flatpak runtime?

**Comment by Zetzun** [comment]
Build 133593 working fine on my laptop Lenovo Legion 5 Slim 14. I had to install ffmpeg flatpak manually for Hardware acceleration to become available and after that it's smooth (tested running on the AMD iGPU with H.265).
Fedora 40 KDE
Kernel: 6.9.7-200.fc40.x86_64

**Comment by Kodikuu** [comment]
> Interesting.. the fact that FFMPEG 6 is being used is a good thing. This means it's touching the codecs from the ffmpeg extension, do you know if all of the VAAPI bits are installed on your WSL2 VM?
> 
> I'm not sure how the AMD hardware you have is being abstracted into the VM, but in a standard install of debian for example, you'd need [mesa-va-drivers](https://packages.debian.org/mesa-va-drivers) to provide all of the libraries for applications on the host, I'd be willing to bet something like that is already installed.
> 
> What kind of output does running [vainfo](https://packages.debian.org/vainfo) give you in WSL2? Is it possible that there's some kind of missing codec in the flatpak runtime?

There is no AMD hardware in the WSL install. By "debian install", I mean installing `parsec-linux.deb`. My vaapi is definitely not set up right for Nvidia, with no driver available according to vainfo, but Nvidia in WSL is weird to begin with

Looking around, it seems CUDA in Flatpak is a problem in general maybe? So I think we can consider the Nvidia decoding not working to be "okay"

**Review by Kodikuu — APPROVED** [review]

**Comment by ProjectSynchro** [comment]
> > Interesting.. the fact that FFMPEG 6 is being used is a good thing. This means it's touching the codecs from the ffmpeg extension, do you know if all of the VAAPI bits are installed on your WSL2 VM?
> > I'm not sure how the AMD hardware you have is being abstracted into the VM, but in a standard install of debian for example, you'd need [mesa-va-drivers](https://packages.debian.org/mesa-va-drivers) to provide all of the libraries for applications on the host, I'd be willing to bet something like that is already installed.
> > What kind of output does running [vainfo](https://packages.debian.org/vainfo) give you in WSL2? Is it possible that there's some kind of missing codec in the flatpak runtime?
> 
> There is no AMD hardware in the WSL install. By "debian install", I mean installing `parsec-linux.deb`. My vaapi is definitely not set up right for Nvidia, with no driver available according to vainfo, but Nvidia in WSL is weird to begin with
> 
> Looking around, it seems CUDA in Flatpak is a problem in general maybe? So I think we can consider the Nvidia decoding not working to be "okay"

Also worth noting that NVIDIA doesn't provide any interfaces for VAAPI, which is a bit of a long standing headache on Linux. The fact Parsec supports NVENC via CUDA means that NVIDIA should work, with VAAPI working for AMD and Intel (presumably). 

It might be worth it to report to the dev team responsible that "Hardware" should make some mention to VAAPI just to make things more obvious.

On my end VAAPI works on my discrete RDNA3 card, @Zetzun also has it working on their AMD iGPU.

**Comment by Kodikuu** [comment]
> It might be worth it to report to the dev team responsible that "Hardware" should make some mention to VAAPI just to make things more obvious.

I'll let myself know at some point :P
"Hardware" is _anything_ FFMPEG supports except CUDA, not specifically VAAPI.

**Comment by Zetzun** [comment]
Hello again, I did an additional quick test to try to launch it on my laptop but using the Nvidia GPU but I couldn't manage to do so.
It launches but still uses the AMD iGPU (parsec is not showing up in nvidia-smi), I tried with the following commands on a wayland session, feel free to let me know if there is any other way to do so and I'll test again.
Note that this is unlikely a Parsec issue, is just the usual problems with Nvidia Optimus + wayland + flatpak. But perhaps you may know how to force it to use the Nvidia gpu.

Here are the commands I used in a KDE 6.1.2 (wayland) session:
`flatpak run --env="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia" com.parsecgaming.parsec`

`flatpak run --env="__NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __GLX_VENDOR_LIBRARY_NAME=nvidia" com.parsecgaming.parsec`

`flatpak run --env="__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only" com.parsecgaming.parsec`

-----------

On the other hand, I also tested switching between Hardware and Software encoders (on the AMD iGPU) and seems to work fine. Hardware H.265 is displayed at the top of the Parsec window and the console outputs the following:

`[D 2024-07-12 20:58:58] FFMPEG 6 Hardware
[4 2024-07-12 20:58:58] FFMPEG 6.1.1 testing hw type 3
[2 2024-07-12 20:58:58] FFMPEG 6.1.1 hw type 3
[2 2024-07-12 20:58:58] FFMPEG format 23
[D 2024-07-12 20:59:20] FFMPEG 6 Hardware
[4 2024-07-12 20:59:20] FFMPEG 6.1.1 testing hw type 3
[2 2024-07-12 20:59:20] FFMPEG 6.1.1 hw type 3
[2 2024-07-12 20:59:20] FFMPEG format 23
[D 2024-07-12 21:00:00] FFMPEG 6 Hardware
[4 2024-07-12 21:00:00] FFMPEG 6.1.1 testing hw type 3
[2 2024-07-12 21:00:00] FFMPEG 6.1.1 hw type 3
[2 2024-07-12 21:00:00] FFMPEG format 23
[D 2024-07-12 21:00:15] FFMPEG 6 Software
[2 2024-07-12 21:00:15] FFMPEG format 12
[D 2024-07-12 21:00:54] FFMPEG 6 Hardware
[4 2024-07-12 21:00:54] FFMPEG 6.1.1 testing hw type 3
[2 2024-07-12 21:00:54] FFMPEG 6.1.1 hw type 3
[2 2024-07-12 21:00:54] FFMPEG format 23
[D 2024-07-12 21:01:44] Client status changed to: -3
`

**Comment by ProjectSynchro** [comment]
> > It might be worth it to report to the dev team responsible that "Hardware" should make some mention to VAAPI just to make things more obvious.
> 
> I'll let myself know at some point :P "Hardware" is _anything_ FFMPEG supports except CUDA, not specifically VAAPI.

Whoops :P
*ping* I guess :sweat_smile: 

I do keep forgetting that there are other acceleration backends, I guess on Linux this would be VDPAU, Vulkan Video (no idea how well supported that is by vendors), VAAPI, AMD VCE, Intel OneAPI and others... Perhaps having some separated options could be nice for some platforms with faulty drivers.

Regardless glad this was able to be merged :)

**Pull request merged**
