### PR TITLE
chore: Upgrade to runtime 23.08

### PR DESCRIPTION
**Pull request by SISheogorath**
This is a potentially breaking change and needs quite some testing. I hope some people from the community can help validate this.

The current runtime 21.08 will go EOL very soon.

### CODE REVIEW

**Comment by alsoGAMER** [comment]
@SISheogorath just tried installing this one, `Server returned status 404`

**Comment by SISheogorath** [comment]
bot build

**Comment by TheGreatDeadOne** [comment]
I tested it here on my machine and everything worked as expected.

**Comment by alsoGAMER** [comment]
Same for me

**Comment by SISheogorath** [comment]
Thank you very much!

**Comment by Antoni690** [comment]
Hello, I'm a steam deck user and before the update it did work well but since the last update  I have an error saying "libavcodec58 not found on your system. [-22]".

**Comment by alsoGAMER** [comment]
do you have `org.freedesktop.platform.ffmpeg-full` 23.08 installed?

**Comment by Antoni690** [comment]
> do you have `org.freedesktop.platform.ffmpeg-full` 23.08 installed?

Hello! Yes I do have the 23.08 version of `org.freedesktop.platform.ffmpeg-full`

**Comment by Rotund** [comment]
I'm getting the same error about libavcodec58 not found. Did the people that claim to have tested this actually connect to a remote computer? The app opens fine, but you can't connect to the remote computer.

**Comment by alsoGAMER** [comment]
@Rotund @Antoni690 i just checked which version of that library is shipped on 23.08 and 22.08 and it seems like we have to rollback the base update, at least until parsec rebuilds the client against newer libavcodec versions (either 59 for 22.08 or 60 for 23.08)

@SISheogorath i'm gonna make a pr asap

**Comment by Antoni690** [comment]
> @Rotund @Antoni690 i just checked which version of that library is shipped on 23.08 and 22.08 and it seems like we have to rollback the base update, at least until parsec rebuilds the client against newer libavcodec versions (either 59 for 22.08 or 60 for 23.08)
> 
> @SISheogorath i'm gonna make a revert pr asap

Thank you, I hope Parsec will update their lib asap!

**Comment by Kodikuu** [comment]
Parsec builds against libavcodec 57, 58, and 59 (yes, all at once)

**Pull request merged**
