### PR TITLE
Add libjpeg dependency

### LINKED ISSUE #31: Parsec flatpak fails to open with "cannot open shared object file" errors
Hi, I'm using Linux Mint 21.1 and trying to run parsec via the flatpak. When I launch it, I get the errors

```
[D 2023-08-08 16:55:08] log: Parsec release[release19] (150-89b, Service: -1, Loader: 7)
[D 2023-08-08 16:55:08] MTY_DeleteFile: 'remove' failed with errno 39
[D 2023-08-08 16:55:08] MTY_SOLoad: libcrypto.so.3: cannot open shared object file: No such file or directory
[D 2023-08-08 16:55:08] MTY_SOLoad: 'dlopen' failed to find 'libcrypto.so.3'
[I 2023-08-08 16:55:08] unprivileged_user=1 enable_webview=0
[D 2023-08-08 16:55:08] MTY_SOLoad: libjpeg.so.8: cannot open shared object file: No such file or directory
[D 2023-08-08 16:55:08] MTY_SOLoad: 'dlopen' failed to find 'libjpeg.so.8'
[D 2023-08-08 16:55:10] MTY_SOLoad: libjpeg.so.8: cannot open shared object file: No such file or directory
[D 2023-08-08 16:55:10] MTY_SOLoad: 'dlopen' failed to find 'libjpeg.so.8'
[D 2023-08-08 16:55:10] mty_rwlock_writer: 'pthread_rwlock_wrlock' failed with error 35
```

I do have both of these libraries installed on my system so I'm unsure why dlopen is failing to find them. I tried setting the LD_LIBRARY_PATH environment variable with no change.

### PR DESCRIPTION
**Pull request by christofferson**
Fixes #31

### CODE REVIEW

**Comment by rakruk** [comment]
Seems to fix my duplicate issue (fixes #32). Thanks!

**Comment by SISheogorath** [comment]
Could you add the metadata for [Flathub external data checker](https://github.com/flathub/flatpak-external-data-checker) to make sure we get automated updates?

**Comment by christofferson** [comment]
> Could you add the metadata for [Flathub external data checker](https://github.com/flathub/flatpak-external-data-checker) to make sure we get automated updates?

Apologies, this is my first experience building a Flatpak and my major goal was to just "make it work" so I ended up copying a source wholesale from another project that previously had the same issue. I'll work on updating it / adding that metadata today.

**Comment by tiritto** [comment]
> Build [58566 successful](https://buildbot.flathub.org/#/builders/6/builds/58566) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/41198/com.parsecgaming.parsec.flatpakref
> ```

I've tested this build for a few hours with the purpose of remote gaming. Everything seems to be working as intended once again.

**Pull request merged**
