### PR TITLE
update-runtime-to-a-supported-version

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by alsoGAMER** [comment]
Did you check on your machine first if parsec works correctly after updating the runtime?
Last time we tried it'd start but then wouldn't connect to any host due to incompatible dependencies.

**Comment by dominikzogg** [comment]
@alsoGAMER its easier to flat the flathubbot doing it and test its outcome. Keep you posted.
Ihaven't checked for the closed reverted PR, so probably mine will be as useless as the old one.

**Comment by dominikzogg** [comment]
@alsoGAMER doesn't look that great

```
flatpak run com.parsecgaming.parsec                                                        
/app/bin/parsec: Zeile 3: [: /home/<myuserbane>/parsecd-150-90c.so: Zweistelliger (binärer) Operator erwartet.
/app/bin/parsec: Zeile 4: /app/extra/bin/parsecd: Datei oder Verzeichnis nicht gefunden
```

My naive approach to make it more official: https://twitter.com/dominikzogg/status/1729875034754494957 (in hope they would upgrade more).

**Comment by alsoGAMER** [comment]
I can't read German, what is it saying?
The error we had last time was different.

**Comment by dominikzogg** [comment]
@alsoGAMER sorry
Zeile: line
Zweistelliger: Double-digit
erwartet: expected
Datei oder Verzeichnis nicht gefunden: file or folder not found

**Comment by alsoGAMER** [comment]
I never saw that before.

**Pull request closed without merging**
